In [52]:
import pandas as pd
import numpy as np

In [53]:
df = pd.DataFrame({
    'Age': [20, 25, 30, 35, np.nan,60],
    'Occupation': ['Finance','Doctor','Professor','Developer',np.nan,'Police'],
    'Salary': [25000,30000,10000,50000,np.nan,30000]
})

df['Age'] = df['Age'].fillna(df['Age'].mean())
df

    Age Occupation   Salary
0  20.0    Finance  25000.0
1  25.0     Doctor  30000.0
2  30.0  Professor  10000.0
3  35.0  Developer  50000.0
4  34.0        NaN      NaN
5  60.0     Police  30000.0

In [54]:
df_ffill = df.copy()
df_ffill['Occupation'] = df_ffill['Occupation'].ffill()
df_ffill

    Age Occupation   Salary
0  20.0    Finance  25000.0
1  25.0     Doctor  30000.0
2  30.0  Professor  10000.0
3  35.0  Developer  50000.0
4  34.0  Developer      NaN
5  60.0     Police  30000.0

In [55]:
df_bfill = df_ffill.copy()
df_bfill['Salary'] = df_bfill['Salary'].bfill()
df_bfill

    Age Occupation   Salary
0  20.0    Finance  25000.0
1  25.0     Doctor  30000.0
2  30.0  Professor  10000.0
3  35.0  Developer  50000.0
4  34.0  Developer  30000.0
5  60.0     Police  30000.0

In [56]:
df_drop_columns = df.dropna()
df_drop_columns

    Age Occupation   Salary
0  20.0    Finance  25000.0
1  25.0     Doctor  30000.0
2  30.0  Professor  10000.0
3  35.0  Developer  50000.0
5  60.0     Police  30000.0