In [12]:
import pandas as pd
import numpy as np

In [13]:
# Exact Duplicates
df = pd.DataFrame(
    {
        'Id': [1, 2, 3, 4, 5, 6, 7, 8, 9, 10],
        'Name': ['JoHn', 'Jane', 'Bob', 'Alice', 'John', 'Jane', 'Bob', 'Alice', 'John', 'Jane'],
        'Age': [25, 30, 35, 40, 25, 30, 35, 40, 25, 30]
    }
)
df_exact = df.drop_duplicates()
df_exact

   Id   Name  Age
0   1   JoHn   25
1   2   Jane   30
2   3    Bob   35
3   4  Alice   40
4   5   John   25
5   6   Jane   30
6   7    Bob   35
7   8  Alice   40
8   9   John   25
9  10   Jane   30

In [14]:
# Subset-Based Removal
df_exact_name = df.drop_duplicates(subset=['Name'])
df_exact_name

   Id   Name  Age
0   1   JoHn   25
1   2   Jane   30
2   3    Bob   35
3   4  Alice   40
4   5   John   25